apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveyform-backend-deployment
  namespace: surveyform
  labels:
    app: surveyform-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: surveyform-backend
  template:
    metadata:
      labels:
        app: surveyform-backend
    spec:
      containers:
        - name: surveyform
          image: devbravo1996/surveyform:0.1
          ports:
            - containerPort: 8080