apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveyform-backend-deployment
  namespace: surveyform-backend
  labels:
    app: surveyform-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: surveyform-backend
  template:
    metadata:
      labels:
        app: surveyform-backend
    spec:
      containers:
        - name: surveyform-backend
          image: devbravo1996/surveyformbackend:1.0.0
          envFrom:
            - configMapRef:
                name: surveyform-backend-configmap
            - secretRef:
                name: surveyform-backend-secret
          ports:
            - containerPort: 8080