apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: surveyform-backend-ingress
  namespace: surveyform
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: surveyform-backend
                port:
                  number: 8080